# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://blackpencil2019.github.io/myblog/
date_format: "ordinal"
title: BLACKPENCIL's CASE
subtitle: "小铅笔盒子"
description: "BLACKPENCIL is not black."
keywords: blackpencil, blog
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
remote_theme: blackpencil2019/myblog
# ---------------- #
#      Author      #
# ---------------- #
author: BLACKPENCIL
organization: 
organization_url: 
github_username: blackpencil2019
location: China
email: blackpencil2015@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: blackpencil2019/myblog2

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: false
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: 
    clientSecret: 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#  Special effect  #
# ---------------- #
se:
    fireworks: true
    canvas_nest: true